## LOCAL CONFIG-CLIENT
# server:
#   port: 8181
#
# spring:
#   application:
#     name: department-service
#   config:
#     import: optional:configserver:http://localhost:8585
#   cloud:
#     config:
#       uri: http://localhost:8585
#   profiles:
#     active: dev

#######################################################

## GITHUB CONFIG-CLIENT
server:
  port: 8181

spring:
  profiles:
    active: dev
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8585"

#######################################################

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true


#######################################################

#feign:
#  client:
#    config:
#      default:
#        read-timeout: 5000
#        metrics:
#          enabled: true
#        logger-level: full
#        connectTimeout: 5000
