server:
  port: 8585

spring:
  application:
    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fsk/spring-boot-cloud-native-config-server
          clone-on-start: true
          try-master-branch: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true